//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package subsonic_api.model;

import org.simpleframework.xml.*;

import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Directory complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Directory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="child" type="{http://subsonic.org/restapi}Child" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="starred" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="userRating" type="{http://subsonic.org/restapi}UserRating" />
 *       &lt;attribute name="averageRating" type="{http://subsonic.org/restapi}AverageRating" />
 *       &lt;attribute name="playCount" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Order(elements = {
        "child"
})
public class Directory {

    @ElementList(inline = true, entry = "child", required = false)
    protected List<Child> child;
    @Attribute(name = "id", required = true)
    protected String id;
    @Attribute(required = false, name = "parent")
    protected String parent;
    @Attribute(name = "name", required = true)
    protected String name;
    // TODO: 10/05/2017 change to date
    @Attribute(required = false, name = "starred")
    @XmlSchemaType(name = "dateTime")
    protected String starred;
    @Attribute(required = false, name = "userRating")
    protected Integer userRating;
    @Attribute(required = false, name = "averageRating")
    protected Double averageRating;
    @Attribute(required = false, name = "playCount")
    protected Long playCount;

    /**
     * Gets the value of the child property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the child property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChild().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Child }
     */
    public List<Child> getChild() {
        if (child == null) {
            child = new ArrayList<Child>();
        }
        return this.child;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the parent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setParent(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the starred property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public String getStarred() {
        return starred;
    }

    /**
     * Sets the value of the starred property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setStarred(String value) {
        this.starred = value;
    }

    /**
     * Gets the value of the userRating property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getUserRating() {
        return userRating;
    }

    /**
     * Sets the value of the userRating property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setUserRating(Integer value) {
        this.userRating = value;
    }

    /**
     * Gets the value of the averageRating property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getAverageRating() {
        return averageRating;
    }

    /**
     * Sets the value of the averageRating property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setAverageRating(Double value) {
        this.averageRating = value;
    }

    /**
     * Gets the value of the playCount property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getPlayCount() {
        return playCount;
    }

    /**
     * Sets the value of the playCount property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setPlayCount(Long value) {
        this.playCount = value;
    }

    @Override
    public String toString() {
        return "Directory{" +
                "child=" + child +
                ", id='" + id + '\'' +
                ", parent='" + parent + '\'' +
                ", name='" + name + '\'' +
                ", starred='" + starred + '\'' +
                ", userRating=" + userRating +
                ", averageRating=" + averageRating +
                ", playCount=" + playCount +
                '}';
    }
}
