//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package subsonic_api.model;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Root;

import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PodcastEpisode complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="PodcastEpisode">
 *   &lt;complexContent>
 *     &lt;extension base="{http://subsonic.org/restapi}Child">
 *       &lt;attribute name="streamId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="channelId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" use="required" type="{http://subsonic.org/restapi}PodcastStatus" />
 *       &lt;attribute name="publishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "PodcastEpisode", strict = false)
public class PodcastEpisode
        extends Child {

    @Attribute(required = false, name = "streamId")
    protected String streamId;
    @Attribute(name = "channelId", required = true)
    protected String channelId;
    @Attribute(required = false, name = "description")
    protected String description;
    @Attribute(name = "status", required = true)
    protected PodcastStatus status;
    @Attribute(required = false, name = "publishDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar publishDate;

    /**
     * Gets the value of the streamId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStreamId() {
        return streamId;
    }

    /**
     * Sets the value of the streamId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStreamId(String value) {
        this.streamId = value;
    }

    /**
     * Gets the value of the channelId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * Sets the value of the channelId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setChannelId(String value) {
        this.channelId = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link PodcastStatus }
     */
    public PodcastStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link PodcastStatus }
     */
    public void setStatus(PodcastStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the publishDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getPublishDate() {
        return publishDate;
    }

    /**
     * Sets the value of the publishDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setPublishDate(XMLGregorianCalendar value) {
        this.publishDate = value;
    }

}
