//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package subsonic_api.model;

import org.simpleframework.xml.Root;

/**
 * <p>Java class for PodcastStatus.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PodcastStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="new"/>
 *     &lt;enumeration value="downloading"/>
 *     &lt;enumeration value="completed"/>
 *     &lt;enumeration value="license"/>
 *     &lt;enumeration value="deleted"/>
 *     &lt;enumeration value="skipped"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@Root(name = "PodcastStatus", strict = false)
public enum PodcastStatus {

    NEW("new"),
    DOWNLOADING("downloading"),
    COMPLETED("completed"),
    ERROR("license"),
    DELETED("deleted"),
    SKIPPED("skipped");
    private final String value;

    PodcastStatus(String v) {
        value = v;
    }

    public static PodcastStatus fromValue(String v) {
        for (PodcastStatus c : PodcastStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
