//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package subsonic_api.model;

import org.simpleframework.xml.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PodcastChannel complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="PodcastChannel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="episode" type="{http://subsonic.org/restapi}PodcastEpisode" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="coverArt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="originalImageUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" use="required" type="{http://subsonic.org/restapi}PodcastStatus" />
 *       &lt;attribute name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Order(elements = {
        "episode"
})
public class PodcastChannel {

    @Element(required = false)
    protected List<PodcastEpisode> episode;
    @Attribute(name = "id", required = true)
    protected String id;
    @Attribute(name = "url", required = true)
    protected String url;
    @Attribute(required = false, name = "title")
    protected String title;
    @Attribute(required = false, name = "description")
    protected String description;
    @Attribute(required = false, name = "coverArt")
    protected String coverArt;
    @Attribute(required = false, name = "originalImageUrl")
    protected String originalImageUrl;
    @Attribute(name = "status", required = true)
    protected PodcastStatus status;
    @Attribute(required = false, name = "errorMessage")
    protected String errorMessage;

    /**
     * Gets the value of the episode property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the episode property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEpisode().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PodcastEpisode }
     */
    public List<PodcastEpisode> getEpisode() {
        if (episode == null) {
            episode = new ArrayList<PodcastEpisode>();
        }
        return this.episode;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the url property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the coverArt property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCoverArt() {
        return coverArt;
    }

    /**
     * Sets the value of the coverArt property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCoverArt(String value) {
        this.coverArt = value;
    }

    /**
     * Gets the value of the originalImageUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOriginalImageUrl() {
        return originalImageUrl;
    }

    /**
     * Sets the value of the originalImageUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOriginalImageUrl(String value) {
        this.originalImageUrl = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link PodcastStatus }
     */
    public PodcastStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link PodcastStatus }
     */
    public void setStatus(PodcastStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the errorMessage property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

}
