//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package subsonic_api.model;

import org.simpleframework.xml.*;


/**
 * <p>Java class for Response complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="musicFolders" type="{http://subsonic.org/restapi}MusicFolders"/>
 *         &lt;element name="indexes" type="{http://subsonic.org/restapi}Indexes"/>
 *         &lt;element name="directory" type="{http://subsonic.org/restapi}Directory"/>
 *         &lt;element name="genres" type="{http://subsonic.org/restapi}Genres"/>
 *         &lt;element name="artists" type="{http://subsonic.org/restapi}ArtistsID3"/>
 *         &lt;element name="artist" type="{http://subsonic.org/restapi}ArtistWithAlbumsID3"/>
 *         &lt;element name="album" type="{http://subsonic.org/restapi}AlbumWithSongsID3"/>
 *         &lt;element name="song" type="{http://subsonic.org/restapi}Child"/>
 *         &lt;element name="videos" type="{http://subsonic.org/restapi}Videos"/>
 *         &lt;element name="videoInfo" type="{http://subsonic.org/restapi}VideoInfo"/>
 *         &lt;element name="nowPlaying" type="{http://subsonic.org/restapi}NowPlaying"/>
 *         &lt;element name="searchResult" type="{http://subsonic.org/restapi}SearchResult"/>
 *         &lt;element name="searchResult2" type="{http://subsonic.org/restapi}SearchResult2"/>
 *         &lt;element name="searchResult3" type="{http://subsonic.org/restapi}SearchResult3"/>
 *         &lt;element name="playlists" type="{http://subsonic.org/restapi}Playlists"/>
 *         &lt;element name="playlist" type="{http://subsonic.org/restapi}PlaylistWithSongs"/>
 *         &lt;element name="jukeboxStatus" type="{http://subsonic.org/restapi}JukeboxStatus"/>
 *         &lt;element name="jukeboxPlaylist" type="{http://subsonic.org/restapi}JukeboxPlaylist"/>
 *         &lt;element name="license" type="{http://subsonic.org/restapi}License"/>
 *         &lt;element name="user" type="{http://subsonic.org/restapi}Users"/>
 *         &lt;element name="user" type="{http://subsonic.org/restapi}User"/>
 *         &lt;element name="chatMessages" type="{http://subsonic.org/restapi}ChatMessages"/>
 *         &lt;element name="albumList" type="{http://subsonic.org/restapi}AlbumList"/>
 *         &lt;element name="albumList2" type="{http://subsonic.org/restapi}AlbumList2"/>
 *         &lt;element name="randomSongs" type="{http://subsonic.org/restapi}Songs"/>
 *         &lt;element name="songsByGenre" type="{http://subsonic.org/restapi}Songs"/>
 *         &lt;element name="lyrics" type="{http://subsonic.org/restapi}Lyrics"/>
 *         &lt;element name="podcasts" type="{http://subsonic.org/restapi}Podcasts"/>
 *         &lt;element name="newestPodcasts" type="{http://subsonic.org/restapi}NewestPodcasts"/>
 *         &lt;element name="internetRadioStations" type="{http://subsonic.org/restapi}InternetRadioStations"/>
 *         &lt;element name="bookmarks" type="{http://subsonic.org/restapi}Bookmarks"/>
 *         &lt;element name="playQueue" type="{http://subsonic.org/restapi}PlayQueue"/>
 *         &lt;element name="shares" type="{http://subsonic.org/restapi}Shares"/>
 *         &lt;element name="starred" type="{http://subsonic.org/restapi}Starred"/>
 *         &lt;element name="starred2" type="{http://subsonic.org/restapi}Starred2"/>
 *         &lt;element name="albumInfo" type="{http://subsonic.org/restapi}AlbumInfo"/>
 *         &lt;element name="artistInfo" type="{http://subsonic.org/restapi}ArtistInfo"/>
 *         &lt;element name="artistInfo2" type="{http://subsonic.org/restapi}ArtistInfo2"/>
 *         &lt;element name="similarSongs" type="{http://subsonic.org/restapi}SimilarSongs"/>
 *         &lt;element name="similarSongs2" type="{http://subsonic.org/restapi}SimilarSongs2"/>
 *         &lt;element name="topSongs" type="{http://subsonic.org/restapi}TopSongs"/>
 *         &lt;element name="license" type="{http://subsonic.org/restapi}Error"/>
 *       &lt;/choice>
 *       &lt;attribute name="status" use="required" type="{http://subsonic.org/restapi}ResponseStatus" />
 *       &lt;attribute name="version" use="required" type="{http://subsonic.org/restapi}Version" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Order(elements = {
        "musicFolders",
        "indexes",
        "directory",
        "genres",
        "artists",
        "artist",
        "album",
        "song",
        "videos",
        "videoInfo",
        "nowPlaying",
        "searchResult",
        "searchResult2",
        "searchResult3",
        "playlists",
        "playlist",
        "jukeboxStatus",
        "jukeboxPlaylist",
        "license",
        "user",
        "user",
        "chatMessages",
        "albumList",
        "albumList2",
        "randomSongs",
        "songsByGenre",
        "lyrics",
        "podcasts",
        "newestPodcasts",
        "internetRadioStations",
        "bookmarks",
        "playQueue",
        "shares",
        "starred",
        "starred2",
        "albumInfo",
        "artistInfo",
        "artistInfo2",
        "similarSongs",
        "similarSongs2",
        "topSongs",
        "license"
})
public class Response {

    @Element(required = false)
    protected MusicFolders musicFolders;
    @Element(required = false)
    protected Indexes indexes;
    @Element(required = false)
    protected Directory directory;
    @Element(required = false)
    protected Genres genres;
    @Element(required = false)
    protected ArtistsID3 artists;
    @Element(required = false)
    protected ArtistWithAlbumsID3 artist;
    @Element(required = false)
    protected AlbumWithSongsID3 album;
    @Element(required = false)
    protected Child song;
    @Element(required = false)
    protected Videos videos;
    @Element(required = false)
    protected VideoInfo videoInfo;
    @Element(required = false)
    protected NowPlaying nowPlaying;
    @Element(required = false)
    protected SearchResult searchResult;
    @Element(required = false)
    protected SearchResult2 searchResult2;
    @Element(required = false)
    protected SearchResult3 searchResult3;
    @Element(required = false)
    protected Playlists playlists;
    @Element(required = false)
    protected PlaylistWithSongs playlist;
    @Element(required = false)
    protected JukeboxStatus jukeboxStatus;
    @Element(required = false)
    protected JukeboxPlaylist jukeboxPlaylist;
    @Element(required = false)
    protected License license;
    @Element(required = false)
    protected Users users;
    @Element(required = false)
    protected User user;
    @Element(required = false)
    protected ChatMessages chatMessages;
    @Element(required = false)
    protected AlbumList albumList;
    @Element(required = false)
    protected AlbumList2 albumList2;
    @Element(required = false)
    protected Songs randomSongs;
    @Element(required = false)
    protected Songs songsByGenre;
    @Element(required = false)
    protected Lyrics lyrics;
    @Element(required = false)
    protected Podcasts podcasts;
    @Element(required = false)
    protected NewestPodcasts newestPodcasts;
    @Element(required = false)
    protected InternetRadioStations internetRadioStations;
    @Element(required = false)
    protected Bookmarks bookmarks;
    @Element(required = false)
    protected PlayQueue playQueue;
    @Element(required = false)
    protected Shares shares;
    @Element(required = false)
    protected Starred starred;
    @Element(required = false)
    protected Starred2 starred2;
    @Element(required = false)
    protected AlbumInfo albumInfo;
    @Element(required = false)
    protected ArtistInfo artistInfo;
    @Element(required = false)
    protected ArtistInfo2 artistInfo2;
    @Element(required = false)
    protected SimilarSongs similarSongs;
    @Element(required = false)
    protected SimilarSongs2 similarSongs2;
    @Element(required = false)
    protected TopSongs topSongs;
    @Element(required = false)
    protected Error error;
    @Attribute(name = "status", required = true)
    protected ResponseStatus status;
    @Attribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the musicFolders property.
     *
     * @return possible object is
     * {@link MusicFolders }
     */
    public MusicFolders getMusicFolders() {
        return musicFolders;
    }

    /**
     * Sets the value of the musicFolders property.
     *
     * @param value allowed object is
     *              {@link MusicFolders }
     */
    public void setMusicFolders(MusicFolders value) {
        this.musicFolders = value;
    }

    /**
     * Gets the value of the indexes property.
     *
     * @return possible object is
     * {@link Indexes }
     */
    public Indexes getIndexes() {
        return indexes;
    }

    /**
     * Sets the value of the indexes property.
     *
     * @param value allowed object is
     *              {@link Indexes }
     */
    public void setIndexes(Indexes value) {
        this.indexes = value;
    }

    /**
     * Gets the value of the directory property.
     *
     * @return possible object is
     * {@link Directory }
     */
    public Directory getDirectory() {
        return directory;
    }

    /**
     * Sets the value of the directory property.
     *
     * @param value allowed object is
     *              {@link Directory }
     */
    public void setDirectory(Directory value) {
        this.directory = value;
    }

    /**
     * Gets the value of the genres property.
     *
     * @return possible object is
     * {@link Genres }
     */
    public Genres getGenres() {
        return genres;
    }

    /**
     * Sets the value of the genres property.
     *
     * @param value allowed object is
     *              {@link Genres }
     */
    public void setGenres(Genres value) {
        this.genres = value;
    }

    /**
     * Gets the value of the artists property.
     *
     * @return possible object is
     * {@link ArtistsID3 }
     */
    public ArtistsID3 getArtists() {
        return artists;
    }

    /**
     * Sets the value of the artists property.
     *
     * @param value allowed object is
     *              {@link ArtistsID3 }
     */
    public void setArtists(ArtistsID3 value) {
        this.artists = value;
    }

    /**
     * Gets the value of the artist property.
     *
     * @return possible object is
     * {@link ArtistWithAlbumsID3 }
     */
    public ArtistWithAlbumsID3 getArtist() {
        return artist;
    }

    /**
     * Sets the value of the artist property.
     *
     * @param value allowed object is
     *              {@link ArtistWithAlbumsID3 }
     */
    public void setArtist(ArtistWithAlbumsID3 value) {
        this.artist = value;
    }

    /**
     * Gets the value of the album property.
     *
     * @return possible object is
     * {@link AlbumWithSongsID3 }
     */
    public AlbumWithSongsID3 getAlbum() {
        return album;
    }

    /**
     * Sets the value of the album property.
     *
     * @param value allowed object is
     *              {@link AlbumWithSongsID3 }
     */
    public void setAlbum(AlbumWithSongsID3 value) {
        this.album = value;
    }

    /**
     * Gets the value of the song property.
     *
     * @return possible object is
     * {@link Child }
     */
    public Child getSong() {
        return song;
    }

    /**
     * Sets the value of the song property.
     *
     * @param value allowed object is
     *              {@link Child }
     */
    public void setSong(Child value) {
        this.song = value;
    }

    /**
     * Gets the value of the videos property.
     *
     * @return possible object is
     * {@link Videos }
     */
    public Videos getVideos() {
        return videos;
    }

    /**
     * Sets the value of the videos property.
     *
     * @param value allowed object is
     *              {@link Videos }
     */
    public void setVideos(Videos value) {
        this.videos = value;
    }

    /**
     * Gets the value of the videoInfo property.
     *
     * @return possible object is
     * {@link VideoInfo }
     */
    public VideoInfo getVideoInfo() {
        return videoInfo;
    }

    /**
     * Sets the value of the videoInfo property.
     *
     * @param value allowed object is
     *              {@link VideoInfo }
     */
    public void setVideoInfo(VideoInfo value) {
        this.videoInfo = value;
    }

    /**
     * Gets the value of the nowPlaying property.
     *
     * @return possible object is
     * {@link NowPlaying }
     */
    public NowPlaying getNowPlaying() {
        return nowPlaying;
    }

    /**
     * Sets the value of the nowPlaying property.
     *
     * @param value allowed object is
     *              {@link NowPlaying }
     */
    public void setNowPlaying(NowPlaying value) {
        this.nowPlaying = value;
    }

    /**
     * Gets the value of the searchResult property.
     *
     * @return possible object is
     * {@link SearchResult }
     */
    public SearchResult getSearchResult() {
        return searchResult;
    }

    /**
     * Sets the value of the searchResult property.
     *
     * @param value allowed object is
     *              {@link SearchResult }
     */
    public void setSearchResult(SearchResult value) {
        this.searchResult = value;
    }

    /**
     * Gets the value of the searchResult2 property.
     *
     * @return possible object is
     * {@link SearchResult2 }
     */
    public SearchResult2 getSearchResult2() {
        return searchResult2;
    }

    /**
     * Sets the value of the searchResult2 property.
     *
     * @param value allowed object is
     *              {@link SearchResult2 }
     */
    public void setSearchResult2(SearchResult2 value) {
        this.searchResult2 = value;
    }

    /**
     * Gets the value of the searchResult3 property.
     *
     * @return possible object is
     * {@link SearchResult3 }
     */
    public SearchResult3 getSearchResult3() {
        return searchResult3;
    }

    /**
     * Sets the value of the searchResult3 property.
     *
     * @param value allowed object is
     *              {@link SearchResult3 }
     */
    public void setSearchResult3(SearchResult3 value) {
        this.searchResult3 = value;
    }

    /**
     * Gets the value of the playlists property.
     *
     * @return possible object is
     * {@link Playlists }
     */
    public Playlists getPlaylists() {
        return playlists;
    }

    /**
     * Sets the value of the playlists property.
     *
     * @param value allowed object is
     *              {@link Playlists }
     */
    public void setPlaylists(Playlists value) {
        this.playlists = value;
    }

    /**
     * Gets the value of the playlist property.
     *
     * @return possible object is
     * {@link PlaylistWithSongs }
     */
    public PlaylistWithSongs getPlaylist() {
        return playlist;
    }

    /**
     * Sets the value of the playlist property.
     *
     * @param value allowed object is
     *              {@link PlaylistWithSongs }
     */
    public void setPlaylist(PlaylistWithSongs value) {
        this.playlist = value;
    }

    /**
     * Gets the value of the jukeboxStatus property.
     *
     * @return possible object is
     * {@link JukeboxStatus }
     */
    public JukeboxStatus getJukeboxStatus() {
        return jukeboxStatus;
    }

    /**
     * Sets the value of the jukeboxStatus property.
     *
     * @param value allowed object is
     *              {@link JukeboxStatus }
     */
    public void setJukeboxStatus(JukeboxStatus value) {
        this.jukeboxStatus = value;
    }

    /**
     * Gets the value of the jukeboxPlaylist property.
     *
     * @return possible object is
     * {@link JukeboxPlaylist }
     */
    public JukeboxPlaylist getJukeboxPlaylist() {
        return jukeboxPlaylist;
    }

    /**
     * Sets the value of the jukeboxPlaylist property.
     *
     * @param value allowed object is
     *              {@link JukeboxPlaylist }
     */
    public void setJukeboxPlaylist(JukeboxPlaylist value) {
        this.jukeboxPlaylist = value;
    }

    /**
     * Gets the value of the license property.
     *
     * @return possible object is
     * {@link License }
     */
    public License getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     *
     * @param value allowed object is
     *              {@link License }
     */
    public void setLicense(License value) {
        this.license = value;
    }

    /**
     * Gets the value of the user property.
     *
     * @return possible object is
     * {@link Users }
     */
    public Users getUsers() {
        return users;
    }

    /**
     * Sets the value of the user property.
     *
     * @param value allowed object is
     *              {@link Users }
     */
    public void setUsers(Users value) {
        this.users = value;
    }

    /**
     * Gets the value of the user property.
     *
     * @return possible object is
     * {@link User }
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     *
     * @param value allowed object is
     *              {@link User }
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the chatMessages property.
     *
     * @return possible object is
     * {@link ChatMessages }
     */
    public ChatMessages getChatMessages() {
        return chatMessages;
    }

    /**
     * Sets the value of the chatMessages property.
     *
     * @param value allowed object is
     *              {@link ChatMessages }
     */
    public void setChatMessages(ChatMessages value) {
        this.chatMessages = value;
    }

    /**
     * Gets the value of the albumList property.
     *
     * @return possible object is
     * {@link AlbumList }
     */
    public AlbumList getAlbumList() {
        return albumList;
    }

    /**
     * Sets the value of the albumList property.
     *
     * @param value allowed object is
     *              {@link AlbumList }
     */
    public void setAlbumList(AlbumList value) {
        this.albumList = value;
    }

    /**
     * Gets the value of the albumList2 property.
     *
     * @return possible object is
     * {@link AlbumList2 }
     */
    public AlbumList2 getAlbumList2() {
        return albumList2;
    }

    /**
     * Sets the value of the albumList2 property.
     *
     * @param value allowed object is
     *              {@link AlbumList2 }
     */
    public void setAlbumList2(AlbumList2 value) {
        this.albumList2 = value;
    }

    /**
     * Gets the value of the randomSongs property.
     *
     * @return possible object is
     * {@link Songs }
     */
    public Songs getRandomSongs() {
        return randomSongs;
    }

    /**
     * Sets the value of the randomSongs property.
     *
     * @param value allowed object is
     *              {@link Songs }
     */
    public void setRandomSongs(Songs value) {
        this.randomSongs = value;
    }

    /**
     * Gets the value of the songsByGenre property.
     *
     * @return possible object is
     * {@link Songs }
     */
    public Songs getSongsByGenre() {
        return songsByGenre;
    }

    /**
     * Sets the value of the songsByGenre property.
     *
     * @param value allowed object is
     *              {@link Songs }
     */
    public void setSongsByGenre(Songs value) {
        this.songsByGenre = value;
    }

    /**
     * Gets the value of the lyrics property.
     *
     * @return possible object is
     * {@link Lyrics }
     */
    public Lyrics getLyrics() {
        return lyrics;
    }

    /**
     * Sets the value of the lyrics property.
     *
     * @param value allowed object is
     *              {@link Lyrics }
     */
    public void setLyrics(Lyrics value) {
        this.lyrics = value;
    }

    /**
     * Gets the value of the podcasts property.
     *
     * @return possible object is
     * {@link Podcasts }
     */
    public Podcasts getPodcasts() {
        return podcasts;
    }

    /**
     * Sets the value of the podcasts property.
     *
     * @param value allowed object is
     *              {@link Podcasts }
     */
    public void setPodcasts(Podcasts value) {
        this.podcasts = value;
    }

    /**
     * Gets the value of the newestPodcasts property.
     *
     * @return possible object is
     * {@link NewestPodcasts }
     */
    public NewestPodcasts getNewestPodcasts() {
        return newestPodcasts;
    }

    /**
     * Sets the value of the newestPodcasts property.
     *
     * @param value allowed object is
     *              {@link NewestPodcasts }
     */
    public void setNewestPodcasts(NewestPodcasts value) {
        this.newestPodcasts = value;
    }

    /**
     * Gets the value of the internetRadioStations property.
     *
     * @return possible object is
     * {@link InternetRadioStations }
     */
    public InternetRadioStations getInternetRadioStations() {
        return internetRadioStations;
    }

    /**
     * Sets the value of the internetRadioStations property.
     *
     * @param value allowed object is
     *              {@link InternetRadioStations }
     */
    public void setInternetRadioStations(InternetRadioStations value) {
        this.internetRadioStations = value;
    }

    /**
     * Gets the value of the bookmarks property.
     *
     * @return possible object is
     * {@link Bookmarks }
     */
    public Bookmarks getBookmarks() {
        return bookmarks;
    }

    /**
     * Sets the value of the bookmarks property.
     *
     * @param value allowed object is
     *              {@link Bookmarks }
     */
    public void setBookmarks(Bookmarks value) {
        this.bookmarks = value;
    }

    /**
     * Gets the value of the playQueue property.
     *
     * @return possible object is
     * {@link PlayQueue }
     */
    public PlayQueue getPlayQueue() {
        return playQueue;
    }

    /**
     * Sets the value of the playQueue property.
     *
     * @param value allowed object is
     *              {@link PlayQueue }
     */
    public void setPlayQueue(PlayQueue value) {
        this.playQueue = value;
    }

    /**
     * Gets the value of the shares property.
     *
     * @return possible object is
     * {@link Shares }
     */
    public Shares getShares() {
        return shares;
    }

    /**
     * Sets the value of the shares property.
     *
     * @param value allowed object is
     *              {@link Shares }
     */
    public void setShares(Shares value) {
        this.shares = value;
    }

    /**
     * Gets the value of the starred property.
     *
     * @return possible object is
     * {@link Starred }
     */
    public Starred getStarred() {
        return starred;
    }

    /**
     * Sets the value of the starred property.
     *
     * @param value allowed object is
     *              {@link Starred }
     */
    public void setStarred(Starred value) {
        this.starred = value;
    }

    /**
     * Gets the value of the starred2 property.
     *
     * @return possible object is
     * {@link Starred2 }
     */
    public Starred2 getStarred2() {
        return starred2;
    }

    /**
     * Sets the value of the starred2 property.
     *
     * @param value allowed object is
     *              {@link Starred2 }
     */
    public void setStarred2(Starred2 value) {
        this.starred2 = value;
    }

    /**
     * Gets the value of the albumInfo property.
     *
     * @return possible object is
     * {@link AlbumInfo }
     */
    public AlbumInfo getAlbumInfo() {
        return albumInfo;
    }

    /**
     * Sets the value of the albumInfo property.
     *
     * @param value allowed object is
     *              {@link AlbumInfo }
     */
    public void setAlbumInfo(AlbumInfo value) {
        this.albumInfo = value;
    }

    /**
     * Gets the value of the artistInfo property.
     *
     * @return possible object is
     * {@link ArtistInfo }
     */
    public ArtistInfo getArtistInfo() {
        return artistInfo;
    }

    /**
     * Sets the value of the artistInfo property.
     *
     * @param value allowed object is
     *              {@link ArtistInfo }
     */
    public void setArtistInfo(ArtistInfo value) {
        this.artistInfo = value;
    }

    /**
     * Gets the value of the artistInfo2 property.
     *
     * @return possible object is
     * {@link ArtistInfo2 }
     */
    public ArtistInfo2 getArtistInfo2() {
        return artistInfo2;
    }

    /**
     * Sets the value of the artistInfo2 property.
     *
     * @param value allowed object is
     *              {@link ArtistInfo2 }
     */
    public void setArtistInfo2(ArtistInfo2 value) {
        this.artistInfo2 = value;
    }

    /**
     * Gets the value of the similarSongs property.
     *
     * @return possible object is
     * {@link SimilarSongs }
     */
    public SimilarSongs getSimilarSongs() {
        return similarSongs;
    }

    /**
     * Sets the value of the similarSongs property.
     *
     * @param value allowed object is
     *              {@link SimilarSongs }
     */
    public void setSimilarSongs(SimilarSongs value) {
        this.similarSongs = value;
    }

    /**
     * Gets the value of the similarSongs2 property.
     *
     * @return possible object is
     * {@link SimilarSongs2 }
     */
    public SimilarSongs2 getSimilarSongs2() {
        return similarSongs2;
    }

    /**
     * Sets the value of the similarSongs2 property.
     *
     * @param value allowed object is
     *              {@link SimilarSongs2 }
     */
    public void setSimilarSongs2(SimilarSongs2 value) {
        this.similarSongs2 = value;
    }

    /**
     * Gets the value of the topSongs property.
     *
     * @return possible object is
     * {@link TopSongs }
     */
    public TopSongs getTopSongs() {
        return topSongs;
    }

    /**
     * Sets the value of the topSongs property.
     *
     * @param value allowed object is
     *              {@link TopSongs }
     */
    public void setTopSongs(TopSongs value) {
        this.topSongs = value;
    }

    /**
     * Gets the value of the license property.
     *
     * @return possible object is
     * {@link Error }
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the license property.
     *
     * @param value allowed object is
     *              {@link Error }
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link ResponseStatus }
     */
    public ResponseStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link ResponseStatus }
     */
    public void setStatus(ResponseStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersion(String value) {
        this.version = value;
    }


    @Override
    public String toString() {
        return "Response{" +
                "error=" + error +
                ", status=" + status +
                ", version='" + version + '\'' +
                ", musicFolders=" + musicFolders +
                ", indexes=" + indexes +
                ", directory=" + directory +
                ", genres=" + genres +
                ", artists=" + artists +
                ", artist=" + artist +
                ", album=" + album +
                ", song=" + song +
                ", videos=" + videos +
                ", videoInfo=" + videoInfo +
                ", nowPlaying=" + nowPlaying +
                ", searchResult=" + searchResult +
                ", searchResult2=" + searchResult2 +
                ", searchResult3=" + searchResult3 +
                ", playlists=" + playlists +
                ", playlist=" + playlist +
                ", jukeboxStatus=" + jukeboxStatus +
                ", jukeboxPlaylist=" + jukeboxPlaylist +
                ", license=" + license +
                ", user=" + users +
                ", user=" + user +
                ", chatMessages=" + chatMessages +
                ", albumList=" + albumList +
                ", albumList2=" + albumList2 +
                ", randomSongs=" + randomSongs +
                ", songsByGenre=" + songsByGenre +
                ", lyrics=" + lyrics +
                ", podcasts=" + podcasts +
                ", newestPodcasts=" + newestPodcasts +
                ", internetRadioStations=" + internetRadioStations +
                ", bookmarks=" + bookmarks +
                ", playQueue=" + playQueue +
                ", shares=" + shares +
                ", starred=" + starred +
                ", starred2=" + starred2 +
                ", albumInfo=" + albumInfo +
                ", artistInfo=" + artistInfo +
                ", artistInfo2=" + artistInfo2 +
                ", similarSongs=" + similarSongs +
                ", similarSongs2=" + similarSongs2 +
                ", topSongs=" + topSongs +
                '}';
    }
}
