//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package subsonic_api.model;

import org.simpleframework.xml.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SearchResult complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="SearchResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="match" type="{http://subsonic.org/restapi}Child" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="offset" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="totalHits" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Order(elements = {
        "match"
})
public class SearchResult {

    @Element(required = false)
    protected List<Child> match;
    @Attribute(name = "offset", required = true)
    protected int offset;
    @Attribute(name = "totalHits", required = true)
    protected int totalHits;

    /**
     * Gets the value of the match property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the match property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatch().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Child }
     */
    public List<Child> getMatch() {
        if (match == null) {
            match = new ArrayList<Child>();
        }
        return this.match;
    }

    /**
     * Gets the value of the offset property.
     */
    public int getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     */
    public void setOffset(int value) {
        this.offset = value;
    }

    /**
     * Gets the value of the totalHits property.
     */
    public int getTotalHits() {
        return totalHits;
    }

    /**
     * Sets the value of the totalHits property.
     */
    public void setTotalHits(int value) {
        this.totalHits = value;
    }

}
