//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package subsonic_api.model;

import org.simpleframework.xml.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for VideoInfo complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="VideoInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="captions" type="{http://subsonic.org/restapi}Captions" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="audioTrack" type="{http://subsonic.org/restapi}AudioTrack" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="conversion" type="{http://subsonic.org/restapi}VideoConversion" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Order(elements = {
        "captions",
        "audioTrack",
        "conversion"
})
public class VideoInfo {

    @Element(required = false)
    protected List<Captions> captions;
    @Element(required = false)
    protected List<AudioTrack> audioTrack;
    @Element(required = false)
    protected List<VideoConversion> conversion;
    @Attribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the captions property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the captions property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaptions().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Captions }
     */
    public List<Captions> getCaptions() {
        if (captions == null) {
            captions = new ArrayList<Captions>();
        }
        return this.captions;
    }

    /**
     * Gets the value of the audioTrack property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audioTrack property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudioTrack().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AudioTrack }
     */
    public List<AudioTrack> getAudioTrack() {
        if (audioTrack == null) {
            audioTrack = new ArrayList<AudioTrack>();
        }
        return this.audioTrack;
    }

    /**
     * Gets the value of the conversion property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conversion property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConversion().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VideoConversion }
     */
    public List<VideoConversion> getConversion() {
        if (conversion == null) {
            conversion = new ArrayList<VideoConversion>();
        }
        return this.conversion;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

}
