//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package com.fxsalazar.subsonic_api.model;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Order;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ArtistWithAlbumsID3 complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="ArtistWithAlbumsID3">
 *   &lt;complexContent>
 *     &lt;extension base="{http://subsonic.org/restapi}ArtistID3">
 *       &lt;sequence>
 *         &lt;element name="album" type="{http://subsonic.org/restapi}AlbumID3" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Order(elements = {
        "album"
})
public class ArtistWithAlbumsID3
        extends ArtistID3 {

    @ElementList(inline = true, entry = "album", required = false)
    protected List<AlbumID3> album;

    /**
     * Gets the value of the album property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the album property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlbum().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlbumID3 }
     */
    public List<AlbumID3> getAlbum() {
        if (album == null) {
            album = new ArrayList<AlbumID3>();
        }
        return this.album;
    }

    @Override
    public String toString() {
        return "ArtistWithAlbumsID3{" +
                "album=" + album +
                "}\n";
    }
}
