//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package com.fxsalazar.subsonic_api.model;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Order;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ArtistInfo2 complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="ArtistInfo2">
 *   &lt;complexContent>
 *     &lt;extension base="{http://subsonic.org/restapi}ArtistInfoBase">
 *       &lt;sequence>
 *         &lt;element name="similarArtist" type="{http://subsonic.org/restapi}ArtistID3" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Order(elements = {
        "similarArtist"
})
public class ArtistInfo2
        extends ArtistInfoBase {

    @Element(required = false)
    protected List<ArtistID3> similarArtist;

    /**
     * Gets the value of the similarArtist property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the similarArtist property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimilarArtist().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArtistID3 }
     */
    public List<ArtistID3> getSimilarArtist() {
        if (similarArtist == null) {
            similarArtist = new ArrayList<ArtistID3>();
        }
        return this.similarArtist;
    }

}
