//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package com.fxsalazar.subsonic_api.model;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Root;

import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * <p>Java class for JukeboxStatus complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="JukeboxStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="currentIndex" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="playing" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="gain" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "JukeboxStatus", strict = false)
@XmlSeeAlso({
        JukeboxPlaylist.class
})
public class JukeboxStatus {

    @Attribute(name = "currentIndex", required = true)
    protected int currentIndex;
    @Attribute(name = "playing", required = true)
    protected boolean playing;
    @Attribute(name = "gain", required = true)
    protected float gain;
    @Attribute(required = false, name = "position")
    protected Integer position;

    /**
     * Gets the value of the currentIndex property.
     */
    public int getCurrentIndex() {
        return currentIndex;
    }

    /**
     * Sets the value of the currentIndex property.
     */
    public void setCurrentIndex(int value) {
        this.currentIndex = value;
    }

    /**
     * Gets the value of the playing property.
     */
    public boolean isPlaying() {
        return playing;
    }

    /**
     * Sets the value of the playing property.
     */
    public void setPlaying(boolean value) {
        this.playing = value;
    }

    /**
     * Gets the value of the gain property.
     */
    public float getGain() {
        return gain;
    }

    /**
     * Sets the value of the gain property.
     */
    public void setGain(float value) {
        this.gain = value;
    }

    /**
     * Gets the value of the position property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setPosition(Integer value) {
        this.position = value;
    }

}
