//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package com.fxsalazar.subsonic_api.model;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Root;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


/**
 * <p>Java class for License complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="License">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="valid" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="email" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="licenseExpires" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="trialExpires" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "License", strict = false)
public class License {

    @Attribute(name = "valid")
    protected boolean valid;
    @Attribute(required = false, name = "email")
    protected String email;
    // TODO: 08/05/2017 change to date
    @Attribute(required = false, name = "licenseExpires")
    protected String licenseExpires;
    // TODO: 08/05/2017 change to date
    @Attribute(required = false, name = "trialExpires")
    protected String trialExpires;

    /**
     * Gets the value of the valid property.
     */
    public boolean isValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     */
    public void setValid(boolean value) {
        this.valid = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the licenseExpires property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public String getLicenseExpires() {
        return licenseExpires;
    }

    /**
     * Sets the value of the licenseExpires property.
     *
     * @param value allowed object is
     *              {@link Date }
     */
    public void setLicenseExpires(String value) {
        this.licenseExpires = value;
    }

    /**
     * Gets the value of the trialExpires property.
     *
     * @return possible object is
     * {@link Date }
     */
    public String getTrialExpires() {
        return trialExpires;
    }

    /**
     * Sets the value of the trialExpires property.
     *
     * @param value allowed object is
     *              {@link Date }
     */
    public void setTrialExpires(String value) {
        this.trialExpires = value;
    }

    @Override
    public String toString() {
        return "License{" +
                "valid=" + valid +
                ", email='" + email + '\'' +
                ", licenseExpires='" + licenseExpires + '\'' +
                ", trialExpires='" + trialExpires + '\'' +
                '}';
    }
}
