//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package com.fxsalazar.subsonic_api.model;

import org.simpleframework.xml.Root;

/**
 * <p>Java class for MediaType.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MediaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="music"/>
 *     &lt;enumeration value="podcast"/>
 *     &lt;enumeration value="audiobook"/>
 *     &lt;enumeration value="video"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@Root(name = "MediaType", strict = false)
public enum MediaType {
    music,
    podcast,
    audiobook,
    video;
}
