//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.07 at 04:18:52 PM CEST 
//


package com.fxsalazar.subsonic_api.model;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Root;

/**
 * <p>Java class for NowPlayingEntry complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="NowPlayingEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{http://subsonic.org/restapi}Child">
 *       &lt;attribute name="username" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minutesAgo" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="playerId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="playerName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "NowPlayingEntry", strict = false)
public class NowPlayingEntry
        extends Child {

    @Attribute(name = "username", required = true)
    protected String username;
    @Attribute(name = "minutesAgo", required = true)
    protected int minutesAgo;
    @Attribute(name = "playerId", required = true)
    protected int playerId;
    @Attribute(required = false, name = "playerName")
    protected String playerName;

    /**
     * Gets the value of the username property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the minutesAgo property.
     */
    public int getMinutesAgo() {
        return minutesAgo;
    }

    /**
     * Sets the value of the minutesAgo property.
     */
    public void setMinutesAgo(int value) {
        this.minutesAgo = value;
    }

    /**
     * Gets the value of the playerId property.
     */
    public int getPlayerId() {
        return playerId;
    }

    /**
     * Sets the value of the playerId property.
     */
    public void setPlayerId(int value) {
        this.playerId = value;
    }

    /**
     * Gets the value of the playerName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * Sets the value of the playerName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPlayerName(String value) {
        this.playerName = value;
    }

}
